version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URI=mongodb://db:27017/rentomovo
    depends_on:
      - db
  db:
    image: "mongo:latest"

