version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_KEY: "$(cat ~/.ssh/id_rsa)"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mongo:latest"

